name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 19.2
      uses: actions/setup-node@v2
      with:
        node-version: 19.2

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn release-build

    - name: Run yarn deploy
      run: yarn deploy
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
