name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 19.2
      uses: actions/setup-node@v2
      with:
        node-version: 19.2

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn release-build

    - name: Run yarn deploy
      run: |
        git remote set-url origin https://git:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
        yarn deploy
